version: 1.0
input_format: "SCORM"
output_format: "xAPI"
mappings:
  - description: "Convert SCORM student ID to xAPI actor mbox"
    input_fields: "cmi.core.student_id" # doit correspondre au key
    output_field: "actor.mbox"
    transformation: "lambda val: 'mailto:' + val if val else None"

  - description: "Copy SCORM student name to xAPI actor name"
    input_fields: "cmi.core.student_name"
    output_fields: 
        multiple:
        - description: "Transform verb for SCORM book"
          output_field: "verb.id"
          transformation: "lambda: 'http://example.com/verbs/read'"
        - description: "Transform object for SCORM book"
          output_field: "object.id.type"
          transformation: "Book"
    transformation: "lambda val: val"

  - description: "Map SCORM lesson status to xAPI verb id"
    input_fields: "cmi.core.lesson_status"
    output_field: "verb.id"
    transformation: >
      lambda val: {
        'completed': 'http://example.com/xapi/verbs/completed',
        'passed': 'http://example.com/xapi/verbs/passed',
        'failed': 'http://example.com/xapi/verbs/failed',
        'accessed': 'http://example.com/xapi/verbs/accessed'
      }.get(val, None)

  - description: "Format SCORM lesson location to xAPI object id IRI"
    input_fields: "cmi.core.lesson_location"
    output_fields: "object.id"
    transformation:
      custom:
        - "lambda val: 'http://example.com/activities/' + val if val else None"
        - "lambda val: val + '?' if val else None"
      value: ""
      switch:
        - condition: "lambda val: val == 'book'"
          multiple:
          - description: "Transform verb for SCORM book"
            output_field: "verb.id"
            transformation: "lambda: 'http://example.com/verbs/read'"
          - description: "Transform object for SCORM book"
            output_field: "object.id.type"
            transformation: "Book"
        - condition: "lambda val: val == 'quizz'"
          output_field: "verb_id"
          transformation: "http://example.com/verbs/passed-quiz"
        - condition: "True"
          output_field: "verb_id"
          transformation: "http://adlnet.gov/expapi/verbs/used"

  - description: "Copy SCORM raw score to xAPI result score"
    input_fields: 
        - "cmi.core.score.raw"
    output_field: "result.score.raw"
    transformation: "lambda val: float(val) if val else None"

  - description: "Determine xAPI verb and object based on SCORM object type"
    input_fields: 
        - "cmi.object.type"
    tranformation:
      

# Define default values for target format fields if source field is missing
default_values:
  - output_field: "datetime storage"
    value: "default_value"

# Specify additional metadata or global settings
metadata:
  author: Your Name
  version: 1.0
  description: >
    Brief description of the transformation config.
  date:
    publication: ""
    update: ""